# Generated by Django 3.1.2 on 2023-08-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230801_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
