# Generated by Django 4.2.3 on 2023-07-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='Модель')),
                ('image', models.CharField(max_length=300, verbose_name='Изображение')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('release_date', models.DateTimeField(verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
